package javaapplication4;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class calculador extends javax.swing.JFrame {
   private String cadenanumeros= "";
   private String operaciones= "cal";
   private double primernumero , resultado;
   private boolean activado = true;
   private boolean punto = true;
   
    /**
     * Creates new form calculador
     */
    public calculador() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botoneliminar = new javax.swing.JButton();
        botonraiz = new javax.swing.JButton();
        botondivision = new javax.swing.JButton();
        botoneliminarporpartes = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonmultiplicacion = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonresta = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonsuma = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonpunto = new javax.swing.JButton();
        botonigual = new javax.swing.JButton();
        txtpantallaR = new javax.swing.JLabel();
        txtpantallaO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        botoneliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botoneliminar.setText("C");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneliminar);

        botonraiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonraiz.setText("√");
        botonraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonraizActionPerformed(evt);
            }
        });
        jPanel1.add(botonraiz);

        botondivision.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botondivision.setText("/");
        botondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondivisionActionPerformed(evt);
            }
        });
        jPanel1.add(botondivision);

        botoneliminarporpartes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botoneliminarporpartes.setText("CE");
        botoneliminarporpartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarporpartesActionPerformed(evt);
            }
        });
        jPanel1.add(botoneliminarporpartes);

        boton7.setBackground(new java.awt.Color(204, 204, 204));
        boton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        jPanel1.add(boton7);

        boton8.setBackground(new java.awt.Color(204, 204, 204));
        boton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        jPanel1.add(boton8);

        boton9.setBackground(new java.awt.Color(204, 204, 204));
        boton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        jPanel1.add(boton9);

        botonmultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonmultiplicacion.setText("x");
        botonmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(botonmultiplicacion);

        boton4.setBackground(new java.awt.Color(204, 204, 204));
        boton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        jPanel1.add(boton4);

        boton5.setBackground(new java.awt.Color(204, 204, 204));
        boton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        jPanel1.add(boton5);

        boton6.setBackground(new java.awt.Color(204, 204, 204));
        boton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        jPanel1.add(boton6);

        botonresta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonresta.setText("-");
        botonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestaActionPerformed(evt);
            }
        });
        jPanel1.add(botonresta);

        boton1.setBackground(new java.awt.Color(204, 204, 204));
        boton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);

        boton2.setBackground(new java.awt.Color(204, 204, 204));
        boton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2);

        boton3.setBackground(new java.awt.Color(204, 204, 204));
        boton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(boton3);

        botonsuma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonsuma.setText("+");
        botonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumaActionPerformed(evt);
            }
        });
        jPanel1.add(botonsuma);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setText("+/-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);

        boton0.setBackground(new java.awt.Color(204, 204, 204));
        boton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        jPanel1.add(boton0);

        botonpunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonpunto.setText(".");
        botonpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpuntoActionPerformed(evt);
            }
        });
        jPanel1.add(botonpunto);

        botonigual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonigual.setText("=");
        botonigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonigualActionPerformed(evt);
            }
        });
        jPanel1.add(botonigual);

        txtpantallaR.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtpantallaR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtpantallaR.setText("0");

        txtpantallaO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpantallaO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpantallaR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpantallaO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpantallaO, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpantallaR, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
    if(txtpantallaR.getText().equals("0")){
       cadenanumeros="0";
    }else{
        cadenanumeros+="0";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;
    }//GEN-LAST:event_boton0ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
     if(txtpantallaR.getText().equals("0")){
       cadenanumeros="1";
    }else{
        cadenanumeros+="1";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;
    
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
      if(txtpantallaR.getText().equals("0")){
       cadenanumeros="2";
    }else{
        cadenanumeros+="2";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;
   
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
      if(txtpantallaR.getText().equals("0")){
       cadenanumeros="3";
    }else{
        cadenanumeros+="3";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;
    punto = true;
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
     if(txtpantallaR.getText().equals("0")){
       cadenanumeros="4";
    }else{
        cadenanumeros+="4";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;

    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
      if(txtpantallaR.getText().equals("0")){
       cadenanumeros="5";
    }else{
        cadenanumeros+="5";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;

    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
     if(txtpantallaR.getText().equals("0")){
       cadenanumeros="6";
    }else{
        cadenanumeros+="6";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;

    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
      if(txtpantallaR.getText().equals("0")){
       cadenanumeros="7";
    }else{
        cadenanumeros+="7";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;
    
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
         if(txtpantallaR.getText().equals("0")){
       cadenanumeros="8";
    }else{
        cadenanumeros+="8";
    }
   txtpantallaR.setText(cadenanumeros);
    activado= true;
  
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
         if(txtpantallaR.getText().equals("0")){
       cadenanumeros="9";
    }else{
        cadenanumeros+="9";
    }
   txtpantallaR.setText(cadenanumeros);
    activado = true;
   
    }//GEN-LAST:event_boton9ActionPerformed

    private void botonsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumaActionPerformed
     if(activado == true){
         primernumero = Double.parseDouble(cadenanumeros);
         txtpantallaO.setText(cadenanumeros + " + ");
         cadenanumeros = "";
         operaciones = "sumar";
         activado = false;
         
     }
    }//GEN-LAST:event_botonsumaActionPerformed

    private void botonigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonigualActionPerformed
      double segundonumero;
    if(operaciones.equals("cal")){
        txtpantallaR.setText(cadenanumeros); 
     }
     else if(operaciones.equals("restar")){
         segundonumero = Double.parseDouble(cadenanumeros);
         resultado = primernumero - segundonumero;
         txtpantallaR.setText(String.format("% .2f",resultado));
         cadenanumeros = String.valueOf(resultado);
         operaciones = "cal";
         txtpantallaO.setText("");
         
     }
     else if(operaciones.equals("sumar")){
         segundonumero = Double.parseDouble(cadenanumeros);
         resultado = primernumero + segundonumero;
         txtpantallaR.setText(String.format("% .2f",resultado));
         cadenanumeros = String.valueOf(resultado);
         operaciones = "cal";
         txtpantallaO.setText("");
     }
      else if(operaciones.equals("multiplicar")){
         segundonumero = Double.parseDouble(cadenanumeros);
         resultado = primernumero * segundonumero;
         txtpantallaR.setText(String.format("% .2f",resultado));
         cadenanumeros = String.valueOf(resultado);
         operaciones = "cal";
         txtpantallaO.setText("");
     }
      else if(operaciones.equals("dividir")){
         segundonumero = Double.parseDouble(cadenanumeros);
         if(segundonumero == 0){
           txtpantallaR.setText("NoSeDividePor0");
         }else{resultado = primernumero / segundonumero;
         txtpantallaR.setText(String.format("% .2f",resultado));
         cadenanumeros = String.valueOf(resultado);
         operaciones = "cal";
            txtpantallaO.setText(""); 
         }
     }
    
     activado = true;
    }//GEN-LAST:event_botonigualActionPerformed

    private void botonmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiplicacionActionPerformed
   if(activado == true){
         primernumero = Double.parseDouble(cadenanumeros);
         txtpantallaO.setText(cadenanumeros + " * ");
         cadenanumeros = "";
         operaciones = "multiplicar";
         activado = false;
         
     }
    }//GEN-LAST:event_botonmultiplicacionActionPerformed

    private void botonrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestaActionPerformed
     if(activado == true){
         primernumero = Double.parseDouble(cadenanumeros);
         txtpantallaO.setText(cadenanumeros + " - ");
         cadenanumeros = "";
         operaciones = "resta";
         activado = false;
        
     }
    }//GEN-LAST:event_botonrestaActionPerformed

    private void botondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondivisionActionPerformed
     if(activado == true){
         primernumero = Double.parseDouble(cadenanumeros);
         txtpantallaO.setText(cadenanumeros + " / ");
         cadenanumeros = "";
         operaciones = "dividir";
         activado = false;
      
     }
    }//GEN-LAST:event_botondivisionActionPerformed

    private void botonraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonraizActionPerformed
    primernumero = Double.parseDouble(cadenanumeros);
    txtpantallaO.setText("sqrt("+cadenanumeros+")");
    resultado = Math.sqrt(primernumero);
    txtpantallaR.setText(String.format("&.2f", resultado));
    cadenanumeros = String.valueOf(resultado);//convertir el valor a cadena 
    
    }//GEN-LAST:event_botonraizActionPerformed

    private void botonpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpuntoActionPerformed
    if(punto == true){
        if(cadenanumeros.equals("")){
            cadenanumeros ="0.";
        }else{
            cadenanumeros += ".";
        }
        txtpantallaR.setText(cadenanumeros);
        punto = false;
      }
    
    }//GEN-LAST:event_botonpuntoActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
    if(cadenanumeros.charAt(0)!='-'){
        cadenanumeros = "-" + cadenanumeros;
    }else{
        cadenanumeros = cadenanumeros.substring(1,cadenanumeros.length());
    }
    txtpantallaR.setText(cadenanumeros);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
    txtpantallaO.setText("");
    txtpantallaR.setText("0");
    operaciones = "cal";
    cadenanumeros = "";
    activado = true;
    punto = true ;
    
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botoneliminarporpartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarporpartesActionPerformed
    int tamaño = cadenanumeros.length();
    if(tamaño > 0)
        if(tamaño == 1){
            cadenanumeros = "0";
        }else{
            cadenanumeros = cadenanumeros.substring(0,cadenanumeros.length() - 1);
        }
    txtpantallaR.setText(cadenanumeros);
    }//GEN-LAST:event_botoneliminarporpartesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botondivision;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botoneliminarporpartes;
    private javax.swing.JButton botonigual;
    private javax.swing.JButton botonmultiplicacion;
    private javax.swing.JButton botonpunto;
    private javax.swing.JButton botonraiz;
    private javax.swing.JButton botonresta;
    private javax.swing.JButton botonsuma;
    private javax.swing.JButton jButton17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtpantallaO;
    private javax.swing.JLabel txtpantallaR;
    // End of variables declaration//GEN-END:variables
}
